export interface LecceArticle {
  id: string;
  title: string;
  subtitle: string;
  excerpt: string;
  content: string[];
  image: string;
  category: string;
}

export const lecceArticles: LecceArticle[] = [
  {
    id: "1",
    title: "VERSO PISA-LECCE: MENO CUORE, PIÙ CALCOLATRICI",
    subtitle: "Perché la Retorica della Grinta Ci Porterà Dritti in Serie B",
    excerpt:
      'Parliamoci chiaro, sediamoci attorno a un tavolo virtuale e guardiamoci dritti negli occhi, senza i soliti filtri edulcorati da conferenza stampa pre-partita o le rassicurazioni di facciata della dirigenza. La narrazione sportiva italiana è profondamente malata, intossicata da decenni di retorica stantia basata su concetti astratti e, soprattutto, non misurabili.',
    image: "/lecce/pisalecce.png",
    category: "LECCE · TRASFERTE",
    content: [
      `Parliamoci chiaro, sediamoci attorno a un tavolo virtuale e guardiamoci dritti negli occhi, senza i soliti filtri edulcorati da conferenza stampa pre-partita o le rassicurazioni di facciata della dirigenza. La narrazione sportiva italiana è profondamente malata, intossicata da decenni di retorica stantia basata su concetti astratti e, soprattutto, non misurabili. Parliamo costantemente de "il cuore gettato oltre l'ostacolo", de "la grinta da provinciale che non muore mai", de "la maglia sudata fino all'ultima goccia". Tutte fandonie bellissime da leggere sotto l'ombrellone, ma che nel calcio moderno, quello scientifico, spietato e iper-competitivo di questo finale di stagione 2025-2026, equivalgono a tentare di curare una broncopolmonite bilaterale con un infuso tiepido di camomilla.`,
      `Guardare il Lecce di Eusebio Di Francesco in trasferta quest'anno fa venire letteralmente il mal di mare, un senso di profonda nausea tattica che nessuna pacca sulla spalla negli spogliatoi potrà mai curare. La sfida campale del 1° maggio contro il Pisa ci viene già venduta dai media generalisti come la classica, epica "battaglia dove servirà il cuore". Ma la nuda, cruda, quasi offensiva verità è che a Pisa non servirà affatto il cuore: servirà un fottuto miracolo statistico, oppure un drastico e immediato cambio di rotta nei numeri di base della squadra.`,
      `Smettiamo di guardare le facce tese dei giocatori durante il riscaldamento e andiamo a vivisezionare la tabella madre <strong>matchcalendar</strong>, quel meraviglioso e spietato foglio di calcolo che non fa sconti ai sentimenti di nessuno. Se estraiamo i record e analizziamo la colonna <strong>away_xpts</strong> — ovvero i punti attesi generati lontano dall'erba amica del Via del Mare — c'è da far accapponare la pelle anche al più ottimista dei tifosi. I modelli matematici predittivi non mentono: ci dicono chiaramente che le nostre prestazioni esterne sono strutturalmente da retrocessione diretta. Fino ad oggi abbiamo racimolato la miseria di 12 punti in trasferta in tutta la stagione. Dodici. È un numero che non ha bisogno di aggettivi, è una sentenza.`,
      `Il problema sistemico di questa squadra non è solo che non vinciamo fuori casa. Il dramma vero è <em>come</em> non vinciamo. Lo urla a pieni polmoni il dato del <strong>away_ppda</strong> (Passes Allowed Per Defensive Action). Il <strong>PPDA</strong> è l'indicatore principe per misurare l'intensità del pressing: più il numero è alto, più lasci agli avversari la libertà assoluta di scambiarsi il pallone. Ebbene, in trasferta il Lecce semplicemente non pressa. Mai. Zero. Scortiamo i portatori di palla avversari con lo sguardo, mantenendo una distanza di cortesia istituzionale, come fossimo steward incaricati di indicare la via più comoda verso la nostra area di rigore.`,
      `Il differenziale tra gli <strong>away_xG</strong> (quello che la squadra avrebbe dovuto segnare per pura statistica) e gli <strong>away_goals</strong> effettivi è la dimostrazione palese di una squadra a cui tremano le gambe non appena calpesta l'erba degli ultimi sedici metri avversari. C'è un blocco psicologico misurabile matematicamente. I nostri attaccanti, arrivati al momento della conclusione, sembrano avere una crisi di rigetto. E allora, smettiamola con i proclami motivazionali sui social. Quando il nostro sistema di scraping imposterà il flag booleano <strong>is_completed</strong> su TRUE nella tabella matchcalendar, avremo la risposta definitiva alla nostra stagione. A Pisa serve ribaltare il database, non solo gettare il cuore.`,
    ],
  },
  {
    id: "2",
    title:
      "Attacco da Denuncia Penale: 22 Gol, il Mistero delle Coordinate Sballate",
    subtitle: "e l'Arte di Calciare dal Parcheggio",
    excerpt:
      'Ventidue gol in trentaquattro giornate di campionato. Ventidue. C\'è un momento in cui bisogna smettere di appellarsi alla sfortuna, ai pali, alle traverse, ai portieri avversari in giornata di grazia o alle zolle ribelli del terreno di gioco. Quel momento è ampiamente superato.',
    image: "/lecce/stadio.jpg",
    category: "LECCE · ATTACCO",
    content: [
      `Ventidue gol in trentaquattro giornate di campionato. Ventidue. C'è un momento in cui bisogna smettere di appellarsi alla sfortuna, ai pali, alle traverse, ai portieri avversari in giornata di grazia o alle zolle ribelli del terreno di gioco. Quel momento è ampiamente superato. Una media realizzativa di 0,64 gol a partita non è un "periodo di appannamento" o una "sterilità momentanea": è un difetto di fabbrica strutturale, una patologia clinica irreversibile che sta trascinando il Lecce verso il baratro della Serie B. Il recente e anestetizzante pareggio a reti bianche del Bentegodi contro l'Hellas Verona ci è stato propinato come "un punto d'oro su un campo difficile". A questa squadra non manca "il guizzo"; manca proprio l'alfabetizzazione calcistica offensiva di base.`,
      `Per capire l'entità del disastro bisogna aprire i terminali, collegarsi al database e lanciare una query esplorativa, massiva e spietata, sulla tabella <strong>shots</strong>. È lì che si nasconde la verità. Se estraiamo l'intero dataset stagionale e plottiamo su un campo virtuale le coordinate spaziali <strong>X</strong> e <strong>Y</strong> di ogni singolo tiro scoccato dai giallorossi, il grafico di dispersione risultante fa letteralmente sanguinare gli occhi a qualsiasi match analyst. Una squadra funzionale presenta una heat map densa, quasi un grumo rosso fuoco, posizionata all'interno dei sedici metri. Il nostro grafico, invece, assomiglia a un'eruzione cutanea sparsa a casaccio.`,
      `I nostri attaccanti calciano da posizioni geografiche in cui le probabilità di fare gol sfidano le leggi della fisica newtoniana: dalla trequarti, vicino alle bandierine del calcio d'angolo, con il corpo sbilanciato all'indietro a trenta metri di distanza, come se stessero cercando di abbattere un drone anziché centrare una porta larga sette metri. Le conseguenze matematiche di questa follia balistica sono disastrose e le leggiamo chiaramente nella colonna <strong>xG</strong> (Expected Goals): decine di tiri con valore pari a 0.01, 0.02, massimo 0.04. Tradotto dal linguaggio macchina a quello umano: i nostri giocatori prendono sistematicamente decisioni che hanno tra l'1% e il 4% di probabilità di trasformarsi in rete.`,
      `Il quadro clinico si fa ancora più grottesco incrociando queste coordinate con le colonne testuali <strong>situation</strong> e <strong>shot_type</strong>. In un sistema di gioco come quello che teoricamente vorrebbe proporre Di Francesco, ci aspetteremmo una prevalenza schiacciante della voce "Open Play" con tiri puliti. Invece la tabella è infestata da conclusioni generate in situazioni di caos: rimpalli sporchi, mischie furibonde su calci da fermo, seconde palle calciate alla cieca. Il <strong>shot_type</strong> rivela una quantità abnorme di tiri sbilenchi, colpi di testa velleitari fuori equilibrio. Manca totalmente la pulizia del gesto tecnico.`,
      `E qui arriviamo alla radice marcia del problema: il vuoto cosmico nella colonna <strong>player_assisted</strong> e nelle righe di <strong>lastAction</strong>. La maggior parte dei tiri non ha un assistente registrato. Quando invece c'è una voce nella colonna lastAction, non troviamo quasi mai un "Throughball" (filtrante taglia-linee), ma un banale "Pass" orizzontale a venti metri dalla porta. Non esistono triangolazioni veloci, non c'è traccia di inserimenti nello spazio premiati con i tempi giusti. Finché la logica offensiva non verrà radicalmente stravolta, il database continuerà a registrare inesorabilmente nel campo <strong>result</strong> la parola <strong>"Missed"</strong> o, tutt'al più, <strong>"Saved"</strong> — solitamente senza che il portiere debba sporcarsi i guanti.`,
    ],
  },
  {
    id: "3",
    title:
      "Il Buco Nero a Centrocampo: Polmoni d'Acciaio, Piedi Quadrati e la Morte della Geometria",
    subtitle: "Analisi di un Reparto Evaporato",
    excerpt:
      "C'è un momento preciso in cui la stagione del Lecce ha preso una piega irreversibile verso l'abbandono di ogni velleità estetica e costruttiva: la cessione record di Patrick Dorgu al Manchester United durante la finestra di mercato invernale di gennaio 2026.",
    image: "/lecce/difrancesco.png",
    category: "LECCE · CENTROCAMPO",
    content: [
      `C'è un momento preciso in cui la stagione del Lecce ha preso una piega irreversibile verso l'abbandono di ogni velleità estetica e costruttiva: la cessione record di Patrick Dorgu al Manchester United durante la finestra di mercato invernale di gennaio 2026. L'amministratore delegato ha stappato bottiglie di champagne per la plusvalenza capolavoro, ma sul prato verde del Via del Mare si è consumato un dramma tattico silente. Proprio lì, nel cerchio di centrocampo, dove si costruiscono i sogni calcistici e si dettano i ritmi della sopravvivenza in Serie A, si è spenta irrimediabilmente la luce.`,
      `I numeri non provano pietà, non sono corruttibili e non firmano autografi. La tabella <strong>rosters</strong>, che traccia il rendimento di ogni singolo giocatore, si erge a tribunale supremo. Il primo indicatore che colpisce è la colonna <strong>time</strong>: i minutaggi aggregati dei nostri mediani sono spaventosi — i ragazzi macinano chilometri su chilometri. Ma nel calcio, a differenza dell'atletica, correre tanto non serve a nulla se non sai in che direzione correre. E la conferma arriva inesorabile dalla colonna <strong>yellow_card</strong>: il Lecce vanta uno dei centrocampi più sanzionati del campionato. Il cartellino giallo non è indice di "cattiveria agonistica"; nel nostro caso, è il certificato di manifesta inferiorità tecnica.`,
      `Il vero collasso strutturale, l'orrore che certifica la morte della geometria nel Lecce 25/26, si palesa quando spostiamo lo sguardo sulle metriche in double precision <strong>xGBuildup</strong> e <strong>xGChain</strong>. L'<strong>xGBuildup</strong> calcola il valore degli Expected Goals di ogni catena di passaggi a cui un giocatore partecipa, escludendo l'assist finale e il tiro stesso: è il termometro della costruzione pulita del gioco. L'<strong>xGChain</strong> misura il coinvolgimento totale. Ebbene, i valori registrati dai nostri centrocampisti centrali sono un insulto al gioco del calcio. Sono numeri così depressi, così vicini allo zero termico, da richiedere un supporto psicologico per i data analyst che li compilano.`,
      `Costruiamo le azioni dal basso con la stessa grazia di un ippopotamo in una cristalleria. Non appena la palla esce dalla nostra linea difensiva, la manovra si arena in un mare di stucchevoli passaggi orizzontali a due metri, privi di costrutto. Se c'è un campo che urla vendetta nella tabella rosters, quello è <strong>key_passes</strong> — i passaggi chiave che innescano un'occasione da rete: il contatore per i nostri registi ha letteralmente le ragnatele. La colonna <strong>xA</strong> (Expected Assists) è tenuta a galla esclusivamente dai cross disperati e scolastici dei nostri terzini o dalle iniziative individuali degli esterni. Per vie centrali, il Lecce non produce nulla. Niente. Zero assoluto. Un centrocampo che non tiene la palla condanna la difesa all'assedio continuo e l'attacco alla morte per inedia. E in questo momento, i nostri mediani stanno uccidendo la squadra.`,
    ],
  },
  {
    id: "4",
    title: "Il Capolavoro Autolesionista di Tiago Gabriel",
    subtitle:
      "Come Affondare la Difesa (e Forse la Salvezza) in un Pomeriggio di Follia",
    excerpt:
      "La stupidità calcistica, quando si manifesta ai massimi livelli del professionismo, raggiunge vette di puro, incomprensibile autolesionismo che andrebbero studiate nei manuali di psichiatria sportiva prima ancora che a Coverciano.",
    image: "/lecce/corvino.avif",
    category: "LECCE · DIFESA",
    content: [
      `La stupidità calcistica, quando si manifesta ai massimi livelli del professionismo, raggiunge vette di puro, incomprensibile autolesionismo che andrebbero studiate nei manuali di psichiatria sportiva prima ancora che a Coverciano. Prendere un cartellino rosso diretto, totale, inequivocabile e assolutamente inutile a tre giornate dalla fine di un campionato agonico, con la squadra che ha l'acqua alla gola, e con all'orizzonte la trasferta più complessa dell'intero anno solare contro il Pisa. Se dovessimo assegnare un premio per il tempismo peggiore, l'Oscar della follia tattica andrebbe di diritto, con decisione unanime e senza possibilità di appello, a Tiago Gabriel.`,
      `La sua squalifica non è un semplice imprevisto: è una mazzata spaventosa, un cratere apertosi al centro esatto di un reparto difensivo che, seppur tra mille balbettii, ci aveva eroicamente tenuto a galla finora. I 46 gol incassati fino a questo momento — registrati sommando aseticamente i valori <strong>home_goals</strong> e <strong>away_goals</strong> incassati dal nostro <strong>team_id</strong> nella tabella <strong>matchcalendar</strong> — sono un gigantesco specchio per le allodole, un'illusione ottica tenuta in piedi quasi esclusivamente dalla ferocia agonistica del centrale brasiliano. Senza di lui là dietro a fare da diga, a guidare la linea del fuorigioco, a mascherare con le sue letture preventive i difetti strutturali dei compagni, prepariamoci a issare le barricate e a pregare.`,
      `L'impatto reale e devastante di questa assenza lo vedremo stampato nella metrica <strong>away_deep</strong>. L'indicatore "deep completions", tracciato nelle colonne <strong>home_deep</strong> e <strong>away_deep</strong>, misura quante volte permetti all'avversario di completare agevolmente un passaggio a meno di venti metri dalla porta difesa dal tuo portiere. Fino a domenica scorsa, l'aggressività straripante e il senso della posizione di Gabriel fungevano da gigantesco cerotto: usciva forte in anticipo, spezzava le linee di passaggio avversarie prima che la palla penetrasse nei nostri venti metri finali, mantenendo il valore dei deep completions concessi a livelli accettabili.`,
      `I difensori chiamati a sostituire Gabriel compiranno l'errore più vecchio e letale del mondo: si abbasseranno. Rintanandosi al limite dell'area di Falcone, unito al già disastroso <strong>away_ppda</strong> di cui abbiamo già parlato, equivarrà a stendere un tappeto rosso al centrocampo toscano. Il risultato matematico è già scritto nelle proiezioni: l'indice degli <strong>away_xG</strong> concessi schizzerà verso orbite siderali. I modelli predittivi, immuni al tifo, ci restituiscono un campo <strong>ai_verdict</strong> che smette di fornire scenari di equilibrio: preannuncia un potenziale collasso strutturale nelle fasi di transizione negativa. Quando il server aggiornerà il flag <strong>is_scraped</strong> a fine partita, potremmo trovarci di fronte a numeri umilianti, con valori di away_deep concessi degni di una partitella di allenamento. E la colpa, stavolta, sapremo esattamente a chi imputarla — nome, cognome e numero di maglia.`,
    ],
  },
  {
    id: "5",
    title:
      "L'Asilo Nido ci Salverà: Perché Preghiamo all'Altare Laico di San Francesco Camarda",
    subtitle: "L'Unica Speranza Statistica",
    excerpt:
      "È il paradosso calcistico definitivo, la sceneggiatura di un film sportivo distopico talmente grottesco, cinico e implausibile da fare un giro completo su se stesso e trasformarsi, quasi per magia nera, nella nostra unica, disperata, ma tangibile via d'uscita dall'incubo della retrocessione.",
    image: "/lecce/camarda.png",
    category: "LECCE · SPERANZA",
    content: [
      `È il paradosso calcistico definitivo, la sceneggiatura di un film sportivo distopico talmente grottesco, cinico e implausibile da fare un giro completo su se stesso e trasformarsi, quasi per magia nera, nella nostra unica, disperata, ma tangibile via d'uscita dall'incubo della retrocessione. Le residue speranze di salvezza di un club con una storia importante come il Lecce, con a libro paga una rosa di oltre trenta professionisti adulti, vaccinati e ampiamente strapagati, dipendono mani e piedi dal rientro dall'infermeria di un ragazzo che ha festeggiato la maggiore età e preso la patente di guida da poche settimane. Parliamo, ovviamente, di Francesco Camarda.`,
      `Ma attenzione, non facciamoci prendere in giro dalla narrazione stucchevole del "ragazzino d'oro mandato dal cielo". Noi analisti non riponiamo questa incrollabile fiducia in un diciottenne per il romanticismo della sua età. Lo facciamo per un motivo molto più freddo, cinico e inoppugnabile: la nostra unica religione è il database. Basta lanciare una query esplorativa sui suoi record storici nella tabella <strong>rosters</strong> per avere una folgorazione sulla via di Damasco. Lì dentro, tra quelle righe di codice, c'è la dimostrazione matematica e lampante che, in mezzo a un oceano di desolante dilettantismo tattico collettivo, lui è l'unico vero elemento dell'attacco giallorosso capace di giocare a pallone applicando la logica.`,
      `Il rapporto ponderato tra i minuti giocati, registrati nella colonna <strong>time</strong>, e i volumi di gioco che è in grado di produrre parla chiaro. Camarda, a clamorosa differenza di molti suoi blasonati e anziani compagni di reparto, non compie mai, e dico mai, uno scatto o una corsa a vuoto. Le sue movenze sono chirurgiche, programmate per l'efficienza. Il suo valore di <strong>xGChain</strong> ci dice che sa venire incontro, proteggere la sfera, dialogare con i compagni e far salire la squadra, non limitandosi ad aspettare passivamente un pallone che, viste le nostre deficienze a centrocampo, non arriverebbe mai.`,
      `Ma il vero differenziale tecnico, l'abisso che lo separa dai "senatori" dell'attacco, emerge quando incrociamo il suo <strong>player_id</strong> con la tabella <strong>shots</strong>. Se generiamo la mappa di tiro filtrando solo i suoi record, ci troviamo davanti a un'anomalia statistica sconvolgente per i mediocri standard del Lecce attuale: i plot spaziali identificati con le coordinate in double precision <strong>X</strong> e <strong>Y</strong> si trovano quasi esclusivamente all'interno del perimetro dell'area di rigore avversaria. La colonna <strong>situation</strong> registra per lui una percentuale bulgara di <strong>"Open Play"</strong> — azioni manovrate che si concludono con tiri puliti, preparati, geometricamente sensati. Non c'è il caos nei suoi log, non c'è la fretta. Il campo <strong>result</strong> presenta un tasso di pericolosità che nessun altro giocatore in rosa riesce nemmeno a eguagliare da lontano.`,
      `Francesco Camarda non è affatto il futuro prossimo del Lecce — sarebbe un gravissimo errore strategico e intellettuale vederlo in quest'ottica, perché un talento del genere non rimarrà a lungo in un contesto provinciale. Camarda, in questo esatto e drammatico momento storico, è il nostro disperato, unico e insostituibile presente agonistico. Quando lanceremo la simulazione predittiva per la prossima giornata, il campo <strong>ai_verdict</strong> valuterà il suo rientro come la singola variabile più impattante dell'intero campionato. Se per caso dovesse fallire lui in queste ultime tre partite, se non dovesse reggere la pressione assurda di dover salvare un'intera città calcistica da solo, l'algoritmo non mente e non ammette repliche: risparmiate le preghiere, chiudete il database, spegnete i server e iniziate a compilare il modulo per l'iscrizione al prossimo campionato di Serie B. Senza i numeri di questo ragazzino, siamo matematicamente morti.`,
    ],
  },
];
