export interface SassuoloArticle {
  id: string;
  title: string;
  subtitle: string;
  excerpt: string;
  content: string[];
  image: string;
  category: string;
}

export const sassuoloArticles: SassuoloArticle[] = [
  {
    id: "1",
    title: "La Sindrome degli Anni d'Oro: Smettetela di Cercare il Sassuolo di De Zerbi",
    subtitle: "Perché la Nostalgia Sta Uccidendo l'Analisi Obiettiva",
    excerpt:
      "Parliamoci chiaro, guardandoci dritti negli occhi, liberandoci una volta per tutte dalla lente deformante della nostalgia e dalle illusioni ottiche che il calcio a volte regala: l'ombra di Roberto De Zerbi è diventata una vera e propria maledizione per chiunque si sieda oggi sulla panchina del Mapei Stadium.",
    image: "/sassuolo/abbraccio.jpg",
    category: "SASSUOLO · SISTEMA",
    content: [
      `Parliamoci chiaro, guardandoci dritti negli occhi, liberandoci una volta per tutte dalla lente deformante della nostalgia e dalle illusioni ottiche che il calcio a volte regala: l'ombra di Roberto De Zerbi è diventata una vera e propria maledizione per chiunque si sieda oggi sulla panchina del Mapei Stadium. C'è una fetta estremamente rumorosa della tifoseria neroverde, spalleggiata purtroppo da una critica sportiva generalista spesso superficiale, che continua ostinatamente a valutare le prestazioni del Sassuolo 2025/2026 usando il metro di giudizio di una squadra che, molto semplicemente, non esiste più. Quel tridente delle meraviglie composto da Domenico Berardi, Jeremie Boga e Francesco Caputo, supportato dalle geometrie chirurgiche di un centrocampo guidato da Manuel Locatelli che dominava il possesso palla con percentuali bulgare, è un reperto archeologico. Un bellissimo ricordo da conservare negli annali, ma che oggi rappresenta un ostacolo mentale alla comprensione della realtà.`,
      `Se non accettiamo questa brutale verità, non possiamo in alcun modo analizzare oggettivamente i dati della stagione in corso. E i dati estratti dal nostro database, in questo momento esatto della stagione, chiedono tutto tranne che estetica: gridano allarme e richiedono un bagno di crudo pragmatismo.`,
      `I numeri che emergono dai nostri terminali sono un secchio d'acqua ghiacciata per chi cerca ancora il "tiki-taka" in provincia. Prendiamo la produzione offensiva su azione manovrata, che nel calcio contemporaneo è il vero, inequivocabile indicatore della salute creativa e strutturale di una squadra. Ebbene, il Sassuolo ha generato finora un modesto 27.98 xG (Expected Goals) in Open Play. Questo dato è la pietra tombale sull'illusione del bel gioco. Non stiamo parlando di una macchina da guerra del palleggio o di un'orchestra sinfonica capace di mandare in tilt le difese avversarie sulla trequarti. Stiamo parlando di una squadra che fa una fatica immane, quasi fisica, a risalire il campo in modo pulito e organizzato. Il pallone non scorre più fluido tra le linee di passaggio; i filtranti sistematicamente si infrangono sui mediani avversari e le transizioni offensive, un tempo letali e rapide, oggi sono lente, farraginose e spaventosamente prevedibili.`,
      `Il baricentro della squadra si è inevitabilmente e drammaticamente abbassato. Tracciando i parametri del pressing avanzato, notiamo come il PPDA (Passes Allowed Per Defensive Action) sia crollato miseramente rispetto alle medie storiche del club. Questo indicatore specifico ci dice una cosa inequivocabile: il Sassuolo ha smesso di andare a pressare alto per recuperare il pallone in zona offensiva. La squadra oggi preferisce rintanarsi negli ultimi trenta metri, stringere le linee di marcatura e assorbire passivamente l'urto, aspettando un improbabile errore avversario in fase di impostazione piuttosto che forzarlo proattivamente. È una scelta tattica dettata non dalla codardia, ma dalla cronica mancanza di interpreti adatti a sostenere un calcio di puro dominio territoriale. È un pragmatismo che fa a cazzotti con il DNA storico e recente del club, certo, ma che rappresenta l'unica, fragile scialuppa di salvataggio attualmente a disposizione per non affondare.`,
      `Ma è scavando ancora più a fondo nei log difensivi che arriviamo al dato più allarmante. Quello che dovrebbe far tremare i polsi all'allenatore, alla dirigenza e a chiunque legga le statistiche avanzate con un minimo di cognizione di causa: in questa stagione abbiamo concesso agli avversari la mostruosa cifra di 399 tiri su azione. Quasi quattrocento conclusioni scagliate verso la nostra porta nel normale svolgimento del gioco. È un volume di fuoco spaventoso, una grandinata costante, martellante e logorante che una squadra votata al controllo del pallone non concederebbe mai nemmeno in due stagioni intere.`,
      `Cosa significa concedere 400 tiri in Open Play? Significa che non stai in alcun modo gestendo i ritmi della partita; significa che la stai subendo dall'inizio alla fine. Significa che la tua prima linea di pressione è inesistente, che il tuo centrocampo viene regolarmente bypassato con due passaggi in verticale, e che la tua linea difensiva è costantemente sotto assedio, costretta a fare gli straordinari, a raddoppiare marcature disperate e ad affidarsi ai miracoli dell'estremo difensore per tenere il risultato in bilico fino al novantesimo minuto. Questo volume di occasioni concesse non è un incidente di percorso, è un difetto di fabbrica strutturale dell'attuale sistema di gioco.`,
      `Dobbiamo guardare in faccia la realtà: questo Sassuolo ha smesso di essere il salotto buono dell'estetica calcistica italiana. Non siamo più il laboratorio tattico invidiato da mezza Europa, la squadra "simpatia" che faceva tremare le big proponendo un calcio spregiudicato. Il Sassuolo è diventato, per necessità ferrea e per limiti evidenti di rosa, una squadra di trincea. È tempo che l'ambiente metabolizzi questo declassamento tattico. Smettetela di fischiare perplessi dagli spalti del Mapei se il pallone viene spazzato in tribuna senza troppi complimenti quando la pressione si fa insostenibile. Smettetela di pretendere a gran voce un'ostinata e suicida uscita palla a terra dall'area di rigore quando gli attaccanti avversari ci vengono a mordere le caviglie già al limite dell'area piccola.`,
      `Oggi, i punti fondamentali per garantirsi la permanenza nella massima serie passano dal fango, non dai colpi di tacco illuminanti. Passano dai duelli aerei vinti a centrocampo, dai contrasti ruvidi e "sporchi" sulle seconde palle, dalle scivolate disperate alla bandierina del calcio d'angolo al novantacinquesimo minuto di gioco. L'allenatore, a dispetto delle critiche, sembra aver compreso che cercare di replicare un modello di gioco glorioso ma incompatibile con gli attuali interpreti equivale a un suicidio sportivo annunciato.`,
      `La "Sindrome degli Anni d'Oro" è una patologia calcistica pericolosissima, un virus della mente che rischia di offuscare il reale e unico obiettivo stagionale: la cruda sopravvivenza. La matematica avanzata e le statistiche non hanno sentimenti, non tifano e non ricordano le vittorie del passato: analizzano il presente. E il presente ci dice che bisogna cambiare pelle, e in fretta. È arrivato il momento di abbassare la testa, indossare l'elmetto, sporcarsi i pantaloncini di fango e sudore, e accettare che, a volte, per rimanere vivi in Serie A bisogna avere il coraggio e l'umiltà di rinunciare a essere belli.`,
    ],
  },
  {
    id: "2",
    title: "Il Mistero Pinamonti: Condannato dai Numeri o Abbandonato dalla Squadra?",
    subtitle: "Analisi di un Capro Espiatorio Perfetto",
    excerpt:
      "Andrea Pinamonti è diventato, per una sorta di pigra inerzia intellettuale e per la frustrazione di una piazza abituata a ben altri palcoscenici offensivi, il capro espiatorio perfetto della stagione del Sassuolo.",
    image: "/sassuolo/pinamonti.jpg",
    category: "SASSUOLO · ATTACCO",
    content: [
      `Andrea Pinamonti è diventato, per una sorta di pigra inerzia intellettuale e per la frustrazione di una piazza abituata a ben altri palcoscenici offensivi, il capro espiatorio perfetto della stagione del Sassuolo. Quando la squadra non gira, quando la manovra ristagna e il tabellone luminoso rimane ostinatamente inchiodato sullo zero a zero, lo sguardo del tifoso medio e del commentatore generalista si sposta inevitabilmente verso il centro dell'attacco. E lì, sotto la lente d'ingrandimento di una critica spesso feroce e superficiale, c'è il numero nove. La narrativa dominante lo ha già condannato: Pinamonti non segna abbastanza, Pinamonti non è incisivo, Pinamonti non vale l'investimento fatto dalla società, non è l'erede naturale di Scamacca né tantomeno il nuovo Ciccio Caputo.`,
      `Ma in un'epoca in cui il calcio è stato letteralmente decodificato dai dati, limitarsi a guardare la casellina delle reti segnate per giudicare l'impatto di un centravanti è non solo anacronistico, ma rappresenta un vero e proprio insulto all'intelligenza analitica. Dobbiamo alzare il livello del dibattito, aprire i nostri database e sporcarci le mani con le metriche avanzate per capire cosa sta realmente succedendo là davanti.`,
      `Partiamo dai numeri base, quelli crudi, che alimentano il malcontento popolare. Fino a questo momento della stagione 2025/2026, Andrea Pinamonti ha messo a referto 8 gol a fronte di ben 2415 minuti giocati in campionato. Parliamo di una media realizzativa che viaggia su cifre ben lontane da quelle dei top scorer del torneo. La percezione visiva è quella di un attaccante che si è inceppato, che vaga spesso per il campo alla ricerca di palloni giocabili. Ma la colpa risiede interamente nei suoi scarpini o è il sintomo di una disfunzione tattica ben più profonda che affligge l'intero undici titolare?`,
      `Entriamo nel vivo del nostro tool di scouting e incrociamo i dati di produzione offensiva. Il suo indicatore di xG (Expected Goals) totale stagionale si attesta a quota 9.79. Questo è il primo vero spartiacque dell'analisi. Cosa ci dice questo numero? Ci dice che, calcolando la mole, la posizione e la pericolosità intrinseca delle occasioni da rete che Pinamonti ha avuto a disposizione, l'algoritmo si aspettava che segnasse quasi 10 gol. Ne ha fatti 8.`,
      `Qui il livello di scrupolo e di onestà intellettuale deve essere altissimo, senza fare sconti a nessuno: c'è una sottoperformance realizzativa innegabile. Pinamonti sta convertendo meno di quanto produce potenzialmente. Ha lasciato sul piatto quasi due reti "virtuali", dimostrando una fisiologica mancanza di quel cinismo chirurgico, di quella spietatezza da vero "killer" dell'area di rigore che trasforma una mezza occasione in una sentenza capitale. Questo è un limite tecnico e mentale su cui il giocatore deve lavorare. Ma, e c'è un "ma" grosso come le fondamenta del Mapei Stadium, fermarsi a questa constatazione significa ignorare il contesto.`,
      `La vera metrica da vivisezionare per capire il dramma sportivo di Pinamonti è la qualità media delle occasioni che riceve, ovvero il valore medio di xG per singolo tiro. Ed è qui che il banco degli imputati cambia improvvisamente occupante. I palloni che arrivano sui piedi o sulla testa del bomber neroverde sono per la stragrande maggioranza palloni "sporchi", prevedibili, lenti o disperati. Sono il frutto di lanci lunghi dalla difesa scavalcando il centrocampo, o di cross dalla trequarti effettuati con la difesa avversaria ampiamente schierata e in superiorità numerica all'interno dei propri sedici metri.`,
      `Analizzando le metriche di xA (Expected Assists) dei nostri centrocampisti e trequartisti, emerge un vuoto pneumatico di creatività. L'assenza di veri rifinitori, in grado di imbucare il pallone taglialinee o di smarcare l'attaccante davanti al portiere (le famose occasioni "big chance" ad alto coefficiente di xG), sta uccidendo il rendimento del terminale offensivo.`,
      `Come abbiamo evidenziato analizzando il crollo del baricentro di squadra, il Sassuolo oggi si difende basso. Questo significa che quando riconquista il pallone, Pinamonti si trova sistematicamente a quaranta metri dalla porta avversaria, completamente isolato. Gli viene richiesto un lavoro di sponda estenuante, massacrante dal punto di vista fisico e mentale. Deve proteggere palla spalle alla porta, prendere sportellate dai centrali difensivi, far salire la squadra e smistare sulle corsie laterali, per poi buttarsi in area con i polmoni in fiamme sperando in un cross decente, che spesso non arriva perché gli esterni faticano a risalire il campo.`,
      `Pinamonti non è diventato un brocco all'improvviso, e le sue doti balistiche non sono sparite nel nulla. È, drammaticamente, un terminale offensivo depotenziato e isolato in una squadra che ha smesso di produrre gioco pulito sulla trequarti. È un ingranaggio sovrautilizzato per compiti che esulano dalla pura finalizzazione. Chiedergli, in queste condizioni tattiche e di rifornimento, di reggere il peso dell'intero reparto da solo e di mettere a segno 15 o 20 gol stagionali non è solo tatticamente ingenuo, è matematicamente irragionevole.`,
      `I numeri lo inchiodano per qualche errore di troppo sotto porta, è vero, ma lo assolvono ampiamente dall'accusa principale: Andrea Pinamonti è una vittima del sistema Sassuolo molto più di quanto ne sia il problema. Se l'allenatore non troverà il modo di alzare la qualità della rifinitura e di riempire l'area di rigore con gli inserimenti delle mezzali per togliergli la pressione della marcatura a uomo, l'attaccante trentino continuerà a lottare nel fango, collezionando più lividi che gol, sotto i fischi ingenerosi di chi non sa, o non vuole, leggere la partita.`,
    ],
  },
  {
    id: "3",
    title: '"Qui per Restare": Nemanja Matic, l\'Adulto nella Stanza dei Bambini',
    subtitle: "Il Gigante Serbo Come Unica Diga Emotiva e Tattica",
    excerpt:
      'Cosa ci fa un gigante balcanico che ha calcato, da padrone assoluto del centrocampo, i prati di Stamford Bridge, dell\'Old Trafford e dell\'Olimpico di Roma, immerso nella nebbia invernale della via Emilia?',
    image: "/sassuolo/Matic.webp",
    category: "SASSUOLO · CENTROCAMPO",
    content: [
      `Cosa ci fa un gigante balcanico che ha calcato, da padrone assoluto del centrocampo, i prati di Stamford Bridge, dell'Old Trafford e dell'Olimpico di Roma, immerso nella nebbia invernale della via Emilia? Quando il nome di Nemanja Matic è stato accostato al Sassuolo, la reazione pavloviana del grande pubblico e degli addetti ai lavori è stata una miscela di scetticismo e facile ironia. In molti, troppi, hanno pensato all'ennesima, malinconica passerella finale di un giocatore ormai al tramonto della carriera, arrivato in provincia unicamente per svernare, strappare un ingaggio comodo e godersi la pensione anticipata senza le pressioni asfissianti delle grandi piazze.`,
      `E invece, le recenti e spiazzanti dichiarazioni d'amore del centrocampista serbo verso il club neroverde — riassumibili in un perentorio "voglio restare a lungo, mi sento a casa" — hanno fatto saltare il banco. Hanno sorpreso tutti. Tutti, tranne chi sa leggere le statistiche e ha la pazienza di analizzare le dinamiche invisibili che regolano il rettangolo di gioco.`,
      `Per capire il reale, monumentale impatto di Matic sul Sassuolo 2025/2026, dobbiamo innanzitutto sfatare il mito del "vecchio che non corre". Apriamo il database e guardiamo il minutaggio alla voce impiego: il serbo ha già accumulato la bellezza di 2464 minuti in campo. È un dato clamoroso, un'infinità di tempo effettivo per un giocatore della sua stazza e della sua età biologica, che certifica una tenuta fisica impensabile per chi lo considerava un ex atleta. Ma Matic non si limita a passeggiare per il campo: Matic è diventato il polmone tattico imprescindibile, l'equatore attorno al quale ruota, a fatica, tutto il sistema di gioco neroverde.`,
      `Se guardiamo il tabellino nudo e crudo, troviamo un solo gol segnato. Ma valutare Nemanja Matic per il suo apporto in fase di finalizzazione è come valutare un architetto per la sua abilità nel dipingere i muri: stai guardando la cosa sbagliata. Il peso specifico del serbo non si misura in reti o in assist spettacolari, ma in quelle metriche oscure che fanno la differenza tra una squadra che perde con dignità e una che naufraga rovinosamente.`,
      `Senza di lui, il centrocampo del Sassuolo è un colabrodo tattico. In un ecosistema, come abbiamo analizzato nei precedenti report, che subisce quasi 400 tiri su azione e che ha abbassato drasticamente il proprio baricentro, Matic agisce da frangiflutti. È il leader silenzioso delle metriche di interdizione: primeggia nei palloni recuperati e, soprattutto, nei deep completions negati agli avversari. La sua abilità nelle letture preventive è da manuale del calcio: dove non arriva più con lo scatto, arriva con un secondo di anticipo grazie al cervello, posizionandosi esattamente sulla linea di passaggio, sporcando le traiettorie e costringendo le mezzali avversarie a ricominciare la manovra.`,
      `Ma c'è un aspetto ancora più profondo che sfugge ai dati puramente numerici e abbraccia la psicologia dello sport. Il Sassuolo, per sua stessa natura aziendale, è un organico infarcito di giovani talenti. Ragazzi di grande prospettiva ma inevitabilmente umorali, incostanti, pronti ad esaltarsi per un dribbling riuscito quanto a deprimersi e scomparire dal campo al primo errore grave. In questo spogliatoio spesso schizofrenico, Matic rappresenta "l'adulto nella stanza".`,
      `È il baricentro emotivo della squadra. Quando i ritmi si alzano vertiginosamente e la squadra va in apnea, affossata dal pressing avversario, è lui che calamita il pallone, usa il fisico in protezione, subisce il fallo intelligente e congela il gioco, permettendo ai compagni di respirare e riposizionarsi. Quando c'è da alzare la voce, lo fa. Quando c'è da spendere il classico "cartellino giallo tattico" per stroncare una ripartenza letale a campo aperto, il serbo non si tira mai indietro, dimostrando una lucidità cinica che ai compagni più giovani manca quasi del tutto.`,
      `L'intelligenza posizionale di Matic è, oggi, l'unica vera diga posizionata davanti a una difesa che altrimenti verrebbe spazzata via a ogni transizione negativa. Non è solo un giocatore in mezzo al campo, è l'estensione del braccio dell'allenatore sul terreno di gioco, è la polizza assicurativa sulla vita tattica di una squadra in perenne equilibrio precario. Il fatto che voglia restare non è la ricerca di un rifugio comodo, ma la consapevolezza di aver trovato un ecosistema che ha un disperato, vitale bisogno del suo cervello, molto prima che dei suoi muscoli. Se il Sassuolo riuscirà a mantenere la categoria, gran parte del merito sarà passata silenziosamente dai tacchetti di questo inossidabile gigante venuto dai Balcani.`,
    ],
  },
  {
    id: "4",
    title: "Fortezza di Carta: Il Miracolo Statistico della Difesa Neroverde",
    subtitle: "Quando la Dea Bendata Tiene in Piedi un Castello di Sabbia",
    excerpt:
      "Se soffrite di cuore, se siete facilmente impressionabili o se semplicemente preferite vivere nell'illusione rassicurante che il calcio sia uno sport dominato unicamente dal caso, vi sconsigliamo vivamente di addentrarvi nell'analisi dei log difensivi del Sassuolo 2025/2026.",
    image: "/sassuolo/Stadio.jpg",
    category: "SASSUOLO · DIFESA",
    content: [
      `Se soffrite di cuore, se siete facilmente impressionabili o se semplicemente preferite vivere nell'illusione rassicurante che il calcio sia uno sport dominato unicamente dal caso, vi sconsigliamo vivamente di addentrarvi nell'analisi dei log difensivi del Sassuolo 2025/2026. C'è un'anomalia statistica così macroscopica, così evidente e sproporzionata, che sta letteralmente facendo impazzire i nostri modelli predittivi e i database di mezza Europa.`,
      `Se ci fermassimo alla superficie, ovvero alla lettura della classifica tradizionale, potremmo quasi tirare un sospiro di sollievo. I 44 gol subiti finora raccontano la storia di un reparto arretrato sicuramente mediocre, ballerino, ma tutto sommato non disastroso. Nel panorama della Serie A, specie nella lotta per non retrocedere, si è visto di molto peggio. Quarantacinque gol sul groppone sono un passivo gestibile, un numero che non condanna a priori. Ma la realtà sottostante, quella che emerge quando spogliamo le partite dei risultati casuali e guardiamo la pura produzione offensiva concessa agli avversari, è letteralmente agghiacciante.`,
      `Il calcolo dei Gol Attesi Contro (la metrica xGA, Expected Goals Against) è lo strumento più spietato che abbiamo per valutare la reale tenuta di una difesa. Misura non i gol effettivamente incassati, ma la probabilità matematica che un tiro concesso si trasformi in rete, basandosi sulla posizione, sul tipo di assist, sulla pressione difensiva e su uno storico di centinaia di migliaia di tiri simili. Ebbene, il dato del Sassuolo rivela che gli avversari, in questa stagione, hanno costruito occasioni nette per segnare ben 57.28 gol.`,
      `Leggete bene questo numero e confrontatelo con i gol subiti: c'è un abisso. C'è un gap positivo di oltre 13 reti tra i gol che il Sassuolo avrebbe matematicamente e logicamente dovuto subire (57.28) e quelli che ha effettivamente incassato (44). Si tratta di un'overperformance difensiva clamorosa, un vero e proprio miracolo statistico degno di uno studio accademico, che rappresenta al momento l'unico e solo motivo per cui la squadra non è sprofondata all'ultimo posto in classifica con mesi di anticipo.`,
      `Ma come si spiega un divario così colossale? In parte, come ovvio, con le prestazioni individuali monumentali di chi difende i pali della nostra porta. Il portiere neroverde si è trovato costretto a indossare il mantello del supereroe, compiendo interventi ad altissimo coefficiente di difficoltà e salvando l'impossibile, sovraperformando la metrica dei Post-Shot Expected Goals (che calcola la probabilità di parare un tiro in base alla traiettoria). In parte, l'anomalia si spiega con l'imprecisione a tratti grottesca degli attaccanti avversari, che hanno sprecato occasioni a porta vuota o calciato in curva palloni che chiedevano solo di essere spinti in rete. Un fattore che potremmo brutalmente riassumere con la parola "Fortuna" (o Luck Index, per i puristi dei dati).`,
      `Ma se c'è una legge spietata, inesorabile e inaggirabile nel calcio data-driven, questa è la "regressione verso la media". La statistica non fa sconti a nessuno, tantomeno all'infinito. Puoi lanciare una moneta e ottenere testa per cinque volte di fila, ma alla lunga, su mille lanci, il risultato tornerà inevitabilmente verso il 50%. Applicato al calcio, questo concetto significa una cosa sola: se continui ostinatamente a concedere caterve di tiri (ricordiamo i quasi 400 tiri su azione citati in precedenza) da posizioni centrali, non contestate e ad alto coefficiente di pericolosità, prima o poi la fortuna finisce. Gli avversari ricominceranno a centrare lo specchio della porta, e i portieri torneranno a parare una percentuale umana di tiri.`,
      `La difesa del Sassuolo, oggi, è una fortezza di carta costruita in mezzo a un uragano. È un castello tenuto in piedi dallo scotch, dai riflessi disperati dell'estremo difensore e dagli errori marchiani degli avversari. Analizzando la mappa dei tiri concessi, vediamo una voragine sanguinosa nella cosiddetta "Zona 14", lo spazio centrale al limite della nostra area di rigore, che viene sistematicamente occupato dagli incursori avversari senza che i nostri mediani riescano a fare filtro. I difensori centrali si ritrovano perennemente esposti all'uno contro uno, costretti a difendere correndo all'indietro o a tentare anticipi disperati fuori tempo.`,
      `L'allenatore deve guardare in faccia questo scempio tattico e correre immediatamente ai ripari. Deve correggere in modo drastico le spaziature tra i reparti, accorciare la squadra, rinunciare magari a un uomo offensivo per blindare la trequarti difensiva. Perché basare la propria salvezza sulla speranza che gli avversari continuino a sbagliare gol fatti è una strategia suicida. La matematica sta suonando un campanello d'allarme assordante: il credito con la Dea Bendata è esaurito. Se questo atteggiamento difensivo passivo e permeabile non verrà modificato, la regressione verso la media si abbatterà sul Sassuolo nel finale di stagione con la violenza di uno tsunami, presentando un conto salatissimo e definitivo.`,
    ],
  },
  {
    id: "5",
    title: "Palle Inattive e Dischetti Stregati: Il Lato Oscuro dei Gol del Sassuolo",
    subtitle: "Dai Corner Letali ai Rigori Falliti, la Schizofrenia dei Numeri",
    excerpt:
      "In un panorama tattico desolante come quello che abbiamo minuziosamente delineato nei precedenti capitoli, sorge spontanea una domanda: come fa questa squadra a fare punti?",
    image: "/sassuolo/corner.jpg",
    category: "SASSUOLO · PALLE INATTIVE",
    content: [
      `In un panorama tattico desolante come quello che abbiamo minuziosamente delineato nei precedenti capitoli — un panorama fatto di possesso palla sterile, baricentro collassato, produzione offensiva asfittica e una difesa che si regge in piedi per puro miracolo statistico — sorge spontanea una domanda che ha quasi i contorni del mistero: come fa questa squadra a fare punti? Se su azione manovrata siamo prevedibili e inoffensivi come un coltello di gomma, da dove arrivano le reti vitali per tenere accesa la fiammella della speranza? La risposta, netta e inequivocabile, ce la fornisce ancora una volta l'analisi cruda dei dati: dai calci piazzati. Il Sassuolo 2025/2026 è diventato, per disperazione o per estrema necessità, una squadra che vive e muore sulle situazioni di palla inattiva.`,
      `C'è un paradosso affascinante e al tempo stesso inquietante nei numeri che stiamo per dissezionare, una vera e propria schizofrenia statistica che divide perfettamente a metà il rendimento della squadra quando il pallone è fermo: da un lato troviamo l'efficienza letale e chirurgica dei calci d'angolo, dall'altro il dramma psicologico e tecnico dei calci di rigore. Due facce della stessa medaglia che raccontano perfettamente i limiti mentali di questo gruppo.`,
      `Partiamo dalle note liete, ovvero dalla miniera d'oro dei corner. I dati in nostro possesso sono clamorosi e certificano un'inversione di tendenza totale rispetto al passato: il Sassuolo ha segnato la bellezza di 9 gol da calcio d'angolo, a fronte di un totale di 7.78 xG generati esclusivamente da queste specifiche situazioni. Questo è l'unico vero dato in forte "overperformance" positiva dell'intero reparto offensivo. Non è un caso, non è fortuna: è la certificazione visiva di un lavoro maniacale svolto in settimana dallo staff tecnico.`,
      `Quando il gioco palla a terra ristagna e le idee latitano, la squadra sa di potersi affidare a uno schema offensivo che funziona alla perfezione. Analizzando i tracciati dei calci d'angolo, notiamo blocchi sistematici eseguiti con una precisione quasi cestistica per liberare l'uomo sul secondo palo, traiettorie a rientrare velenosissime e, soprattutto, una ferocia agonistica nel gioco aereo da parte dei nostri centrali difensivi, che spesso e volentieri si trasformano nei veri bomber della squadra, togliendo letteralmente le castagne dal fuoco a un reparto d'attacco in apnea. È il trionfo del calcio operaio, l'esaltazione del dettaglio in un contesto generale di profonda confusione.`,
      `Ma se i corner rappresentano il paradiso terrestre di questa squadra, il dischetto del rigore è l'accesso diretto ai gironi infernali. E qui l'analisi si fa dolorosa, perché tocca corde psicologiche ancor prima che tecniche. Analizzando la metrica dei penalty, il bilancio è da mani nei capelli. Su 4 rigori a favore calciati (che per definizione statistica equivalgono a un potenziale teorico di circa 3.05 xG, considerando che un rigore medio vale circa 0.76 Expected Goals), il Sassuolo ne ha trasformati solo 2. Stiamo parlando di un modesto, inaccettabile e sanguinante 50% di realizzazione.`,
      `Nel calcio moderno, buttare via un rigore su due è semplicemente un suicidio tattico imperdonabile. Sbagliare dagli undici metri è un lusso che si possono permettere forse squadre come il Manchester City o il Real Madrid, formazioni in grado di generare venti palle gol nitide a partita, per le quali un errore dal dischetto è solo un fastidioso contrattempo. Ma per una squadra come il Sassuolo di quest'anno, in cui, come abbiamo ampiamente dimostrato, la costruzione del gioco latita, la trequarti è un deserto e ogni singola occasione pulita viene partorita con una fatica immane, sprecare il tiro in assoluto più facile del gioco del calcio è un delitto che si paga carissimo in classifica.`,
      `Il rigore sbagliato non è solo un "meno uno" sul tabellino dei gol attesi, è una mazzata psicologica devastante. Infrange il morale di chi lo calcia, deprime i compagni che si erano conquistati l'occasione lottando nel fango dell'area di rigore, ed esalta oltremodo gli avversari e il portiere, cambiando irrimediabilmente l'inerzia emotiva dell'intero match. Perché si sbaglia così tanto? La risposta non è nei piedi, ma nella testa. Manca una leadership chiara, mancano gerarchie granitiche e inscalfibili. Chi si presenta sul dischetto lo fa spesso con le gambe che tremano, consapevole che quell'unico tiro potrebbe essere l'unica vera occasione da gol dell'intera partita. Questo fardello invisibile trasforma un gesto tecnico elementare in un incubo di tensione.`,
      `La conclusione di questa indagine è un monito spietato per l'allenatore: il Sassuolo deve ritrovare immediatamente nervi d'acciaio dagli undici metri. Bisogna chiudere i rigoristi nello spogliatoio, scegliere un "killer" dal sangue freddo e isolarlo dalle pressioni esterne. Perché la corsa salvezza non si deciderà con giocate spettacolari o trame palla a terra degne del Barcellona di Guardiola; si deciderà sui margini, sui dettagli sporchi, sulle palle inattive convertite o fallite. I calci d'angolo ci tengono a galla, ma ogni rigore sbagliato è un passo in più verso il baratro della retrocessione. La matematica, ancora una volta, ha presentato il conto.`,
    ],
  },
];
