import soccerdata as sd
import pandas as pd
pd.set_option('display.max_columns', None)
fbref = sd.FBref(leagues="Big 5 European Leagues Combined", seasons="2526")
print("Fetching schedule...")
schedule = fbref.read_schedule()
print("Shape:", schedule.shape)
print("Columns:", schedule.columns.tolist())
print("\nFirst row:")
print(schedule.iloc[0])
print("\nUnique competitions:", schedule['competition'].unique())
print("\nFetching player match stats...")
player_stats = fbref.read_player_match_stats()
print("Shape:", player_stats.shape)
print("Columns:", player_stats.columns.tolist())
print("\nFirst row:")
print(player_stats.iloc[0])
print("\nFetching shot events...")
shot_events = fbref.read_shot_events()
print("Shape:", shot_events.shape if shot_events is not None else 'None')
if shot_events is not None:
    print("Columns:", shot_events.columns.tolist())
    print("\nFirst row:")
    print(shot_events.iloc[0])